name: clang-format-run-pr

# Controls when the workflow will run
on:
  issue_comment:
      types: [created]

jobs:

  run-on-pr: 
    # Run on branchs, not forked PR branches
    if: |
      contains(github.event.comment.body, '/clang-format-run')

    runs-on:
      - self-hosted
      - software

    steps:

    - name: Clean
      continue-on-error: true
      run: |
        # Remove local modifications
        set +e

        # Attempt to clean the repo
        git scorch
        retval=$?

        # Remove everything if this fails
        if [[ $retval -ne 0 ]]
        then
          rm -rf *
        fi

        set -e

    - uses: actions/github-script@v3
      id: get-pr
      with:
        script: |
          const request = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          }
          core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
          try {
            const result = await github.pulls.get(request)
            return result.data
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`)
          }
    - uses: actions/checkout@v3
      with:
        repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
        ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
        fetch-depth: 0

    - name: clang-format-run
      run: |
          bash -ex .github/workflows/clang-format-run.sh
          
    - name: Push reformatted files
      uses: EndBug/add-and-commit@v9.0.1
      with:
        add: '*'
        message: 'clang-format bot reformatting.'
        push: true
